flowchart TB
  current([current]) -.-> a
  previous([previous]) -.-> n0((nil))

  subgraph a[" "]
    direction LR
    a0[car]:::red
    a1[cdr]:::blue
  end

  subgraph b[" "]
    direction LR
    b0[car]:::red
    b1[cdr]:::blue
  end

  subgraph c[" "]
    direction LR
    c0[car]:::red
    c1[cdr]:::blue
  end

  a0 --> b
  a1 --> c
  b0 --> d1(cons)
  b1 --> d2(cons)
  c0 --> d3(cons)
