flowchart TD
  rt([root]) -.-> a
  cur([current]):::red -.-> a
  prev([previous]):::blue -.-> n0((nil))

  subgraph a["cons A"]
    direction LR
    a0[car]
    a1[cdr]
  end

  subgraph b["cons B"]
    direction LR
    b0[car]
    b1[cdr]
  end

  subgraph c["cons C"]
    direction LR
    c0[car]
    c1[cdr]
  end

  a0 --> b
  a1 --> c
  b0 --> d1(d1)
  b1 --> d2(d2)
  c0 --> d3(d3)
  c1 --> n1((nil))
