name: setup
description: Sets up a CI job
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        package_json_file: doc/package.json
    - uses: actions/setup-node@v4
      with:
        cache: pnpm
        cache-dependency-path: doc/pnpm-lock.yaml
        node-version-file: doc/package.json
    - run: pnpm i --frozen-lockfile
      shell: bash
      working-directory: doc
    - run: sudo apt update --fix-missing
      shell: bash
    - run: sudo apt install fonts-takao texlive-full
      shell: bash
