name: setup
description: Sets up a CI job
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version-file: package.json
    - run: pnpm i --frozen-lockfile
      shell: bash
    - run: sudo apt update --fix-missing
      shell: bash
    - run: sudo apt install fonts-takao
      shell: bash
