name: setup
description: Sets up a CI job
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        cache: npm
        cache-dependency-path: doc/package-lock.json
        node-version-file: doc/package.json
    - run: npm ci
      shell: bash
      working-directory: doc
    - uses: homebrew/actions/setup-homebrew@main
      with:
        stable: true
    - run: brew install texlive
    - run: sudo apt update --fix-missing
      shell: bash
    - run: sudo apt install fonts-takao
      shell: bash
