extend = "muffy.toml"

[sites.main]
roots = ["http://localhost:4321/doc"]
schemes = ["http"]

[sites.slides]
roots = ["http://localhost:4321/doc/slides/"]
ignore = true

[sites.icon]
roots = ["http://localhost:4321/icon.svg"]
statuses = [404]
