flowchart LR
  c0 -.-> d0(#quot;foo#quot;)
  c2 -.-> d0
  c4 -.-> d1(#quot;bar#quot;)

  subgraph s[ ]
    c0[const ] --> c1[call] --> c2
    c2[const] --> c3[call] --> c4
    c4[const] --> c5[call]
  end

  c1 -.-> d2(display)
  c3 -.-> d2
  c5 -.-> d2
