flowchart TB
  subgraph Split
    direction LR

    c0[car . cdrₜ] --> c1[car . cdrₜ]
    c0 --> c1[car . cdrₜ]
  end

  subgraph Merge
    direction LR

    c3[car . cdrₜ] --> c5[car . cdrₜ]
    c4[car . cdrₜ] --> c5
  end
