flowchart LR
  d2(#quot;foo#quot;) -.-> d3
  d2 -.-> d4
  d3(foo) -.-> c1
  d3 -.-> c4
  d4(foo) -.-> c3
  d4 -.-> c5

  subgraph code
    c0[const] --> c1[set] --> c2
    c2[const] --> c3[set] --> c4
    c4[get] --> c5[get] --> c6[call]
  end

  d0(123) -.-> c0
  d1(456) -.-> c2
  d5(+) -.-> c6
