flowchart LR
  d0(123) --> c0
  d1(456) --> c2
  d2(#quot;foo#quot;) --> d3
  d2 --> d4
  d3(foo) --> c1
  d4(foo) --> c3
  c0[const] --> c1[set] --> c2
  c2[const] --> c3[set] --> c4
  c4[if] -->  c5[get 0]
