flowchart LR
  subgraph s0[Merge]
    direction TB

    c0[car . cdrₜ]:::current --> c2[car . cdrₜ]
    c1[car . cdrₜ] --> c2
  end

  s0 -.-> s1

  subgraph s1[Merge]
    direction TB

    c3[car . cdrₜ] --> c5[car . cdrₜ]
    c4[car . cdrₜ] --> c5
  end

 classDef current stroke:red
