flowchart LR
  subgraph s0[Encode pair]
    direction TB

    c0[pair 1]:::blue --> c2[pair 3]
    c1[pair 2] --> c2
  end

  s0 -.-> s1

  subgraph s1[Add to cache]
    direction TB

    c3[pair 1] --> c5[pair 3]:::blue
    c4[pair 2] --> c5
  end

  s1 ~~~ s2

  subgraph s2[Encode pair]
    direction TB

    c6[pair 1] --> c8[pair 3]
    c7[pair 2]:::blue --> c8
  end

  s2 -.-> s3

  subgraph s3[Remove from cache]
    direction TB

    c9[pair 1] --> c11[pair 3]:::red
    c10[pair 2] --> c11
  end
