flowchart LR
  c0 -.->|data reference| d0(x)
  c2 -.-> d1(#quot;foo#quot;)
  c4 -.-> d3(display)

  subgraph s[ ]
    c0[get] -->|control flow| c1{if} --> c2[const] & c3[const] --> c4[call]:::red
  end

  c3 -.-> d2(#quot;bar#quot;)
