flowchart LR
  subgraph s0[foo]
    a0[const 42] --> a1[set x] --> a2[...]
  end

  subgraph s1[bar]
    b0[call foo] --> b1[get 3] --> b2[...]
    b0 --> a0
  end

  s0 -.-> b0

  subgraph s2[ ]
    c0[call bar] --> c1[const 42] --> c2[...]
    c0 --> b0
  end

  s1 -.-> c0
