name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: true
      - uses: ./.github/actions/setup
      - run: node --run build -- --site http://localhost:4321/doc
      - run: node --run lint
      - run: node --run preview &
        working-directory: doc
      - uses: raviqqe/muffy@e6419fa0a4a8210f741b6d46bfd31eb19d1086d1 # v0.3.17
        with:
          config: muffy.local.toml
  markdown_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup
      - run: pnpm oxfmt --check '**/*.md'
  tex_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: cargo install tex-fmt
      - run: tex-fmt -f $(git ls-files *.bib *.tex)
  markdown_link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: true
      - uses: ./.github/actions/setup
      - run: node --run build:image
      - uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          args: --no-progress --verbose README.md
          token: ${{ inputs.github_token }}
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: streetsidesoftware/cspell-action@de2a73e963e7443969755b648a1008f77033c5b2 # v8.4.0
  test:
    needs:
      - build
      - markdown_format
      - tex_format
      - markdown_link
      - spell_check
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
