name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
      - uses: ./.github/actions/setup
      - run: node --run build
      - run: node --run lint
  markdown_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: npx prettier --check '**/*.md'
  tex_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: cargo install tex-fmt
      - run: tex-fmt -f $(git ls-files *.bib *.tex)
  markdown_link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: node --run build:image
      - uses: raviqqe/markdown-link-check@v1
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: streetsidesoftware/cspell-action@main
  test:
    needs:
      - build
      - markdown_format
      - tex_format
      - markdown_link
      - spell_check
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
