name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true
      - uses: ./.github/actions/setup
      - run: node --run build -- --site http://localhost:4321/doc
      - run: node --run lint
      - run: node --run preview &
        working-directory: doc
      - uses: raviqqe/muffy@fa911c6da37ae078d436c255fa229cea107bbf89 # v0.3.11
        with:
          config: muffy.local.toml
  markdown_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: npx oxfmt --check '**/*.md'
  tex_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: cargo install tex-fmt
      - run: tex-fmt -f $(git ls-files *.bib *.tex)
  markdown_link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true
      - uses: ./.github/actions/setup
      - run: node --run build:image
      - uses: raviqqe/markdown-link-check@7cc7ee84bd8a34196095dc004324cd7c134c01f7 # v1.0.5
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: streetsidesoftware/cspell-action@de2a73e963e7443969755b648a1008f77033c5b2 # v8.4.0
  test:
    needs:
      - build
      - markdown_format
      - tex_format
      - markdown_link
      - spell_check
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
